version: '2'

services:
  mysql:
    image: orchardup/mysql
    volumes:
      - ./mysql_db:/var/lib/mysql
    environment:
      MYSQL_USERNAME: root

  mysqladmin:
    image: nazarpc/phpmyadmin
    ports:
      - "3031:80"
    links:
      - mysql

  memcached:
    image: memcached

  php:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile_php 
    links:
      - mysql
      - memcached
    volumes:
      - ./app:/var/www
      - ./composer:/root/.composer/

  nginx:
    image: nginx
    ports:
      - 3030:80
    links:
      - php
    volumes:
      - ./app:/var/www
      - ./nginx:/etc/nginx/
